# This file was generated by GoReleaser. DO NOT EDIT.
cask "sv" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "1cf47f384d0815f69ae393317d714c4a09bce70f0d908897448b1bdc87249756"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3def20b19bb564322f596e5d5fc653fd7cbfd37ab6d3319cc5fcec2852417ac"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "74989926778f4e6c15c061aa691515beccdde2738f24e6149260294902a2ecfc"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e22bf4cafebe1898a90de8833bd653de87e6f566a06080131e5d59122c719b8"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sv"
  desc "SSH host manager for the terminal"
  homepage "https://github.com/kianurivzzz/save-serve-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sv"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sv"]
    end
  end

  generate_completions_from_executable "sv", "completion",
    base_name: "sv",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
