# This file was generated by GoReleaser. DO NOT EDIT.
cask "sv" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "2c8b12b3614b25d700b68dd01aa46ef52dd7b3a6b6ae71f080d963172f17b018"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "afbbf29692ce508bd62b01a6aea05428e1c86ada30f55ba472463ff1c55692cd"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cd481684127d4e0f2f5058d804f3bd45b92de6519c98b3366748e414099316b5"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "97f6ff293448a1a9c86e88e5473b99aae593dd7ded14ab5c6e4a16d5f2fe457d"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sv"
  desc "SSH host manager for the terminal"
  homepage "https://github.com/kianurivzzz/save-serve-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sv"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sv"]
    end
  end

  generate_completions_from_executable "sv", "completion",
    base_name: "sv",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
