# This file was generated by GoReleaser. DO NOT EDIT.
cask "sv" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5a4e4a5a11f560f0f8cc27e68f0819b98fa7bbdf2d54dacf140ff0653651caf2"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kianurivzzz/save-serve-cli/"
    end
    on_intel do
      sha256 "33ea50904a5d5954ac21bb55d1502da344499336246e068d0a929eac0408dccd"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kianurivzzz/save-serve-cli/"
    end
  end
  on_linux do
    on_arm do
      sha256 "18f2c947d39d302566f108fbab5dd6781521af1228156b553625f7b111e903dc"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kianurivzzz/save-serve-cli/"
    end
    on_intel do
      sha256 "8b20c2ff65cc6f35e87b4a92895c7982db902481bf3ea376b78949f66d481a63"
      url "https://github.com/kianurivzzz/save-serve-cli/releases/download/v#{version}/sv_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kianurivzzz/save-serve-cli/"
    end
  end

  name "sv"
  desc "SSH host manager for the terminal"
  homepage "https://github.com/kianurivzzz/save-serve-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sv"]
    end
  end
  generate_completions_from_executable "sv", "completion",
    base_name: "sv",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
